# **A Quick Pandas Tutorial**
> ## *Author* : [Rathachai CHAWUTHAI](https://rathachai.creatier.pro/) , Ph.D
> ### *Affiliation* : Computer Engineering, King Mongkut's Institute of Technology Ladkrabang (KMITL)
> #### *Updated Date* : 2024-12-05
---

> <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.



---

## Prerequisite Knowledge
> Python, List, Dictionary, Tuple, Function, Lambda, Numpy, and CSV


## Agenda

**Review**
*   About a Dataset
*   Basic Numpy

**Pandas**
*   Series & Dataframe
*   Read CSV into a Pandas Dataframe
*   Column Selection
*   Row Selection
*   Row and Column Selection (1)
*   Cell Modification
*   Set Index
*   Row and Column Selection (2)
*   Reset Index
*   Range Selection
*   Conditinal Selection
*   Column Operation
*   New Column
*   Drop Row
*   Drop Column
*   Sorting
*   Grouping
*   Iteration
*   Apply Function
*   Save Dataframe into a CSV file


## About a Dataset

Click [https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv](https://github.com/Rathachai/DA-LAB/blob/gh-pages/datasets/simple-employee-db.csv)

## Import Libraries

In [ ]:
import numpy as np
import pandas as pd

## Basic Numpy

In [ ]:
[1,2,3] + [10,10,10]

[1, 2, 3, 10, 10, 10]

In [ ]:
[1,2,3] * 3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [ ]:
np.array([1,2,3]) + np.array([10,10,10])

array([11, 12, 13])

In [ ]:
np.array([1,2,3]) * 3

array([3, 6, 9])

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [ ]:
np.arange(5,10,2)

array([5, 7, 9])

In [ ]:
np.random.rand(5)

array([0.63604145, 0.94475585, 0.07454761, 0.40201126, 0.97263052])

In [ ]:
np.random.randint(10,20,5)

array([18, 12, 19, 10, 17])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
x = np.arange(0,5)

In [ ]:
x

array([0, 1, 2, 3, 4])

In [ ]:
x.sum()

np.int64(10)

In [ ]:
np.sum(x)

np.int64(10)

In [ ]:
x.mean()

np.float64(2.0)

In [ ]:
x.min()

np.int64(0)

In [ ]:
x.max()

np.int64(4)

In [ ]:
x.std()

np.float64(1.4142135623730951)

In [ ]:
x

array([0, 1, 2, 3, 4])

In [ ]:
x[2]

np.int64(2)

In [ ]:
x[0:3]

array([0, 1, 2])

In [ ]:
x[:3]

array([0, 1, 2])

In [ ]:
x[3:]

In [ ]:
x[-1]

In [ ]:
x[-2]

## Pandas Series & Pandas Dataframe

In [ ]:
s1 = pd.Series([0, 10, 20])

In [ ]:
s1

0     0
1    10
2    20
dtype: int64

In [ ]:
s1.mean()

np.float64(10.0)

In [ ]:
s1.max()

20

In [ ]:
s2 = pd.Series(["A", "B", "C"])

In [ ]:
s2

0    A
1    B
2    C
dtype: object

In [ ]:
df = pd.DataFrame({"name":s2, "working_years":s1})

In [ ]:
df

name  working_years
0    A              0
1    B             10
2    C             20

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
type(s1)

pandas.core.series.Series

In [ ]:
df["name"]

0    A
1    B
2    C
Name: name, dtype: object

In [ ]:
df[["name"]]

name
0    A
1    B
2    C

In [ ]:
type(df["name"])

pandas.core.series.Series

In [ ]:
type(df[["name"]])

pandas.core.frame.DataFrame

## Read CSV into a Pandas Dataframe

In [ ]:
CSV_PATH = "https://rathachai.github.io/DA-LAB/datasets/simple-employee-db.csv"

In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df.head()

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [ ]:
df.tail()

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

## Column Selection

In [ ]:
df["name"]

0        Anda
1      Bordin
2    Chantana
3     Donlaya
4     Ekkasit
5      Fundee
6     Gitiwit
7       Harit
Name: name, dtype: object

In [ ]:
df[["name"]]

name
0      Anda
1    Bordin
2  Chantana
3   Donlaya
4   Ekkasit
5    Fundee
6   Gitiwit
7     Harit

In [ ]:
df[["name", "gender", "age"]]

name  gender  age
0      Anda  female   39
1    Bordin    male   25
2  Chantana  female   29
3   Donlaya  female   39
4   Ekkasit    male   37
5    Fundee  female   35
6   Gitiwit    male   26
7     Harit    male   32

## Row Selection

In [ ]:
df.loc[1]

eid                   E012
name                Bordin
gender                male
department       developer
age                     25
salary             48700.0
working_years            2
birth_place         Phuket
Name: 1, dtype: object

In [ ]:
df.loc[[1]]

eid    name gender department  age   salary  working_years birth_place
1  E012  Bordin   male  developer   25  48700.0              2      Phuket

In [ ]:
df.loc[[1,2,3]]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

## Row and Column Selection (1)

In [ ]:
df.loc[1,["name","age"]]

name    Bordin
age         25
Name: 1, dtype: object

In [ ]:
df.loc[[1], ["name","age"]]

name  age
1  Bordin   25

In [ ]:
df.loc[[1,2,3], ["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [ ]:
df[["name","age"]].loc[[1,2,3]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [ ]:
df.loc[[1,2,3]][["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

## Value Modification

In [ ]:
df[["name","working_years"]]

name  working_years
0      Anda              4
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [ ]:
df.loc[0,"working_years"] = 77

In [ ]:
df[["name","working_years"]]

name  working_years
0      Anda             77
1    Bordin              2
2  Chantana              3
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [ ]:
df.loc[[1,2],"working_years"] = 9999

In [ ]:
df[["name","working_years"]]

name  working_years
0      Anda             77
1    Bordin           9999
2  Chantana           9999
3   Donlaya              8
4   Ekkasit              7
5    Fundee              3
6   Gitiwit              2
7     Harit              5

In [ ]:
df.loc[[1,2],["name","working_years"]] = "MODIFIED"

/tmp/ipython-input-2587201694.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'MODIFIED' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[[1,2],["name","working_years"]] = "MODIFIED"


In [ ]:
df[["name","working_years"]]

name working_years
0      Anda            77
1  MODIFIED      MODIFIED
2  MODIFIED      MODIFIED
3   Donlaya             8
4   Ekkasit             7
5    Fundee             3
6   Gitiwit             2
7     Harit             5

In [ ]:
df

eid      name  gender department  age   salary working_years birth_place
0  E011      Anda  female  developer   39  64200.0            77     Bangkok
1  E012  MODIFIED    male  developer   25  48700.0      MODIFIED      Phuket
2  E013  MODIFIED  female  developer   29  45500.0      MODIFIED    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0             8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0             7  Suphanburi
5  E016    Fundee  female    support   35  56600.0             3      Phuket
6  E017   Gitiwit    male    support   26  42400.0             2  Suphanburi
7  E018     Harit    male     devops   32  67700.0             5     Bangkok

## Reload the Dataframe

In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Set Index

In [ ]:
df.set_index("eid")

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df.set_index("eid", inplace=True)

In [ ]:
df

name  gender department  age   salary  working_years birth_place
eid                                                                       
E011      Anda  female  developer   39  64200.0              4     Bangkok
E012    Bordin    male  developer   25  48700.0              2      Phuket
E013  Chantana  female  developer   29  45500.0              3    Chonburi
E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
E016    Fundee  female    support   35  56600.0              3      Phuket
E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
E018     Harit    male     devops   32  67700.0              5     Bangkok

## Row and Column Selection (2)

In [ ]:
df.loc[["E011","E012"], ["name", "salary"]]

name   salary
eid                  
E011    Anda  64200.0
E012  Bordin  48700.0

In [ ]:
df.iloc[0]

name                  Anda
gender              female
department       developer
age                     39
salary             64200.0
working_years            4
birth_place        Bangkok
Name: E011, dtype: object

In [ ]:
df.iloc[[0]]

name  gender department  age   salary  working_years birth_place
eid                                                                   
E011  Anda  female  developer   39  64200.0              4     Bangkok

In [ ]:
df.iloc[[0,1]]

name  gender department  age   salary  working_years birth_place
eid                                                                     
E011    Anda  female  developer   39  64200.0              4     Bangkok
E012  Bordin    male  developer   25  48700.0              2      Phuket

In [ ]:
df.iloc[[0,1]][["name","gender"]]

name  gender
eid                 
E011    Anda  female
E012  Bordin    male

## Reset Index

In [ ]:
df.reset_index(inplace=True)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Reload the Dataframe



In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

## Range Selection

In [ ]:
df.loc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [ ]:
df.loc[:4]

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [ ]:
df.loc[4:]

eid     name  gender department  age   salary  working_years birth_place
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016   Fundee  female    support   35  56600.0              3      Phuket
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df.loc[1:3,["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

In [ ]:
df.iloc[1:4]

eid      name  gender department  age   salary  working_years birth_place
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi

In [ ]:
df.iloc[1:4][["name","age"]]

name  age
1    Bordin   25
2  Chantana   29
3   Donlaya   39

## Conditional Selection

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df[["working_years"]]

working_years
0              4
1              2
2              3
3              8
4              7
5              3
6              2
7              5

In [ ]:
df["working_years"]>3

0     True
1    False
2    False
3     True
4     True
5    False
6    False
7     True
Name: working_years, dtype: bool

In [ ]:
df[df["working_years"]>3]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df[df["working_years"]>3][["name","working_years", "salary"]]

name  working_years   salary
0     Anda              4  64200.0
3  Donlaya              8  72600.0
4  Ekkasit              7  80500.0
7    Harit              5  67700.0

In [ ]:
df[ (df["working_years"]>3) & (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi

In [ ]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ]

eid     name  gender department  age   salary  working_years birth_place
0  E011     Anda  female  developer   39  64200.0              4     Bangkok
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi
7  E018    Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].iloc[[3]]

eid   name gender department  age   salary  working_years birth_place
7  E018  Harit   male     devops   32  67700.0              5     Bangkok

In [ ]:
df[ (df["working_years"]>3) | (df["salary"]>70000) ].loc[[3]]

eid     name  gender department  age   salary  working_years birth_place
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi

## Column Operation

In [ ]:
df["salary"]

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [ ]:
df["salary"]*12

0    770400.0
1    584400.0
2    546000.0
3    871200.0
4    966000.0
5    679200.0
6    508800.0
7    812400.0
Name: salary, dtype: float64

In [ ]:
df["salary"]*df["working_years"]

0    256800.0
1     97400.0
2    136500.0
3    580800.0
4    563500.0
5    169800.0
6     84800.0
7    338500.0
dtype: float64

## New Column

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi
7  E018     Harit    male     devops   32  67700.0              5     Bangkok

In [ ]:
df["country"] = "Thailand"

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country  
0  Thailand  
1  Thailand  
2  Thailand  
3  Thailand  
4  Thailand  
5  Thailand  
6  Thailand  
7  Thailand

In [ ]:
df["bonus"] = df["salary"]*df["working_years"]

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

## Drop Row

In [ ]:
df.drop(7)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0  
7  Thailand  338500.0

In [ ]:
df.drop(7, inplace=True)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

In [ ]:
df.drop([0,1,2])

eid     name  gender department  age   salary  working_years birth_place  \
3  E014  Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015  Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016   Fundee  female    support   35  56600.0              3      Phuket   
6  E017  Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

## Drop Column

In [ ]:
df.drop("country", axis=1)

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

      bonus  
0  256800.0  
1   97400.0  
2  136500.0  
3  580800.0  
4  563500.0  
5  169800.0  
6   84800.0

In [ ]:
df.drop(["country","bonus"], axis=1)

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   

    country     bonus  
0  Thailand  256800.0  
1  Thailand   97400.0  
2  Thailand  136500.0  
3  Thailand  580800.0  
4  Thailand  563500.0  
5  Thailand  169800.0  
6  Thailand   84800.0

In [ ]:
df.drop(["country","bonus"], axis=1, inplace=True)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place
0  E011      Anda  female  developer   39  64200.0              4     Bangkok
1  E012    Bordin    male  developer   25  48700.0              2      Phuket
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi
5  E016    Fundee  female    support   35  56600.0              3      Phuket
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi

## Reload the Dataframe

In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df

## Sorting

In [ ]:
df.sort_values("salary")

In [ ]:
df.sort_values(["department","salary"])

In [ ]:
df.sort_values("salary", ascending=False)

In [ ]:
df

In [ ]:
df.sort_values("salary", ascending=False, inplace=True)

In [ ]:
df

In [ ]:
df.loc[0:2]

In [ ]:
df.iloc[0:2]

## Grouping

In [ ]:
df

In [ ]:
df.groupby("department")[['salary']].mean()

In [ ]:
df.groupby("department").max()

In [ ]:
df.groupby(["department","gender"])[['age', 'salary', 'working_years']].mean()

In [ ]:
df.groupby(["gender","department"])[['age', 'salary', 'working_years']].mean()

In [ ]:
df_group_obj = df.groupby("department")

In [ ]:
df_group_obj

In [ ]:
df_group_obj[['age', 'salary', 'working_years']].mean()

In [ ]:
df_group_obj.max()

In [ ]:
df.groupby("department").min()

In [ ]:
df.groupby("department").count()

In [ ]:
df.groupby("department")[['age', 'salary', 'working_years']].agg(["mean", "count"])

In [ ]:
df.groupby("department")["age"].agg(["mean", "count"])

In [ ]:
df.groupby("department")[["age"]].agg(["mean", "count"])

In [ ]:
df.groupby("department").agg({"age":"min", "salary":"mean"})

In [ ]:
df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

In [ ]:
dfg = df.groupby("department").agg({"age":["min","max"], "salary":"mean"})

In [ ]:
dfg

In [ ]:
dfg.columns

In [ ]:
dfg[('age','min')]

In [ ]:
dfg[[('age','min'),('salary','mean')]]

In [ ]:
dfg.columns

In [ ]:
["_".join(x) for x in dfg.columns]

In [ ]:
dfg.columns = ["_".join(x) for x in dfg.columns]

In [ ]:
dfg

In [ ]:
dfg[["age_min"]]

In [ ]:
dfg.reset_index()

In [ ]:
dfg.reset_index(inplace=True)

In [ ]:
dfg

## Reload the Dataset

In [ ]:
df = pd.read_csv(CSV_PATH)

In [ ]:
df

## Iteration

In [ ]:
for index, row in df.iterrows():
  print(index)

0
1
2
3
4
5
6
7


In [ ]:
for index, row in df.iterrows():
  print(row["eid"], row["name"], row["salary"])

E011 Anda 64200.0
E012 Bordin 48700.0
E013 Chantana 45500.0
E014 Donlaya 72600.0
E015 Ekkasit 80500.0
E016 Fundee 56600.0
E017 Gitiwit 42400.0
E018 Harit 67700.0


In [ ]:
for index, row in df.iterrows():
  #row["shoud_pay_ot"] = "Something" << is not worked
  if row["salary"]>70000:
    df.loc[index,"should_pay_ot"] = "NO"
  elif row["salary"]>50000:
    df.loc[index,"should_pay_ot"] = "MAY BE"
  else:
    df.loc[index,"should_pay_ot"] = "YES"

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

## Reload the Dataset

In [ ]:
df = pd.read_csv(CSV_PATH)

## Apply Function

In [ ]:
np.log10(1000)

3.0

In [ ]:
df["salary"]

0    64200.0
1    48700.0
2    45500.0
3    72600.0
4    80500.0
5    56600.0
6    42400.0
7    67700.0
Name: salary, dtype: float64

In [ ]:
df["salary"].apply(np.log10)

0    4.807535
1    4.687529
2    4.658011
3    4.860937
4    4.905796
5    4.752816
6    4.627366
7    4.830589
Name: salary, dtype: float64

In [ ]:
df["salary"].apply(np.sqrt)

0    253.377189
1    220.680765
2    213.307290
3    269.443872
4    283.725219
5    237.907545
6    205.912603
7    260.192237
Name: salary, dtype: float64

In [ ]:
def times10(num):
  return num*10

In [ ]:
times10(5)

50

In [ ]:
df["age"]

0    39
1    25
2    29
3    39
4    37
5    35
6    26
7    32
Name: age, dtype: int64

In [ ]:
df["age"].apply(times10)

0    390
1    250
2    290
3    390
4    370
5    350
6    260
7    320
Name: age, dtype: int64

In [ ]:
df["age"].apply(lambda x: x*10)

0    390
1    250
2    290
3    390
4    370
5    350
6    260
7    320
Name: age, dtype: int64

In [ ]:
def consider_ot_payment(salary):
  result = ""
  if salary>70000:
    result = "NO"
  elif salary>50000:
    result = "MAY BE"
  else:
    result = "YES"

  return result

In [ ]:
consider_ot_payment(80000)

'NO'

In [ ]:
consider_ot_payment(60000)

'MAY BE'

In [ ]:
consider_ot_payment(30000)

'YES'

In [ ]:
df["salary"].apply(consider_ot_payment)

0    MAY BE
1       YES
2       YES
3        NO
4        NO
5    MAY BE
6       YES
7    MAY BE
Name: salary, dtype: object

In [ ]:
df["should_pay_ot"] = df["salary"].apply(consider_ot_payment)

In [ ]:
df

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE

## Save into a CSV file

In [ ]:
df.to_csv("employee.csv")

In [ ]:
pd.read_csv("employee.csv")

Unnamed: 0   eid      name  gender department  age   salary  working_years  \
0           0  E011      Anda  female  developer   39  64200.0              4   
1           1  E012    Bordin    male  developer   25  48700.0              2   
2           2  E013  Chantana  female  developer   29  45500.0              3   
3           3  E014   Donlaya  female  marketing   39  72600.0              8   
4           4  E015   Ekkasit    male  marketing   37  80500.0              7   
5           5  E016    Fundee  female    support   35  56600.0              3   
6           6  E017   Gitiwit    male    support   26  42400.0              2   
7           7  E018     Harit    male     devops   32  67700.0              5   

  birth_place should_pay_ot  
0     Bangkok        MAY BE  
1      Phuket           YES  
2    Chonburi           YES  
3    Chonburi            NO  
4  Suphanburi            NO  
5      Phuket        MAY BE  
6  Suphanburi           YES  
7     Bangkok        MAY BE

In [ ]:
df.to_csv("employee1.csv", index=False)

In [ ]:
pd.read_csv("employee1.csv")

eid      name  gender department  age   salary  working_years birth_place  \
0  E011      Anda  female  developer   39  64200.0              4     Bangkok   
1  E012    Bordin    male  developer   25  48700.0              2      Phuket   
2  E013  Chantana  female  developer   29  45500.0              3    Chonburi   
3  E014   Donlaya  female  marketing   39  72600.0              8    Chonburi   
4  E015   Ekkasit    male  marketing   37  80500.0              7  Suphanburi   
5  E016    Fundee  female    support   35  56600.0              3      Phuket   
6  E017   Gitiwit    male    support   26  42400.0              2  Suphanburi   
7  E018     Harit    male     devops   32  67700.0              5     Bangkok   

  should_pay_ot  
0        MAY BE  
1           YES  
2           YES  
3            NO  
4            NO  
5        MAY BE  
6           YES  
7        MAY BE



---
https://rathachai.creatier.pro/

## つづく